In [1]:
#AI建立一個funtion
#資料來源:scores=np.random.randint(50,101,size=(50,5))
#欄位:['國文', '英文', '數學', '自然', '社會']
#索引:'學生' + str(i) for i in range(1, 51)]
#建立一個DataFrame
import numpy as np
import pandas as pd

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df
scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df

科目    國文   英文   數學   自然   社會   總分    平均    排名
學生
學生1   77   93   58   51   84  363  72.6  37.0
學生2   89   57   53   94   65  358  71.6  42.0
學生3   79   79   77   82   60  377  75.4  29.0
學生4   85   56   81   67   87  376  75.2  31.0
學生5   55   96   70   58   59  338  67.6  47.0
學生6   98   55   97   61   82  393  78.6  22.0
學生7   68   59   85   94   61  367  73.4  35.0
學生8   76   78   74   99   79  406  81.2  12.0
學生9   86   85   90   92   69  422  84.4   4.0
學生10  97   53   73   79   70  372  74.4  33.0
學生11  77   94   77   59   54  361  72.2  40.0
學生12  79   64   63   52   68  326  65.2  48.0
學生13  58   52   85   70   94  359  71.8  41.0
學生14  87   79   93   64   75  398  79.6  18.0
學生15  95   65   60   79   97  396  79.2  20.0
學生16  88   52   61   80   93  374  74.8  32.0
學生17  66   80  100   66  100  412  82.4   7.0
學生18  96   82   96   73   97  444  88.8   2.0
學生19  97   76   80   50   79  382  76.4  26.0
學生20  69   79   55   65   77  345  69.0  45.0
學生21  79   94   67   59   90  389  77.8  23.0
學生22  80   87   52  100   82  401  80.2  15.0
學生23  61   78   99   57   68  363  72.6  37.0
學生24  62   76   81   93   98  410  82.0   8.0
學生25  79   75   54   93   81  382  76.4  26.0
學生26  54   84   52   89   79  358  71.6  42.0
學生27  86   70   65   80   63  364  72.8  36.0
學生28  89   98   90   57   51  385  77.0  24.0
學生29  85   91   82   74   75  407  81.4  10.0
學生30  96   92   82   61   70  401  80.2  15.0
學生31  89   73   75   84   77  398  79.6  18.0
學生32  85   66   80   60   93  384  76.8  25.0
學生33  61   87   96   90   74  408  81.6   9.0
學生34  98   81   64   86   70  399  79.8  17.0
學生35  79  100   52   82   90  403  80.6  14.0
學生36  90   90   79   76   87  422  84.4   4.0
學生37  85   85   91   81  100  442  88.4   3.0
學生38  77   65   52   92   77  363  72.6  37.0
學生39  85   87   89   63   82  406  81.2  12.0
學生40  69   95   85   50   95  394  78.8  21.0
學生41  62   65   56   86   74  343  68.6  46.0
學生42  54   73   56   53   66  302  60.4  50.0
學生43  78   63   52   94   94  381  76.2  28.0
學生44  58   61   60   68   79  326  65.2  48.0
學生45  83   54   80   81   79  377  75.4  29.0
學生46  90   79   94   63   91  417  83.4   6.0
學生47  77   58   90   90   55  370  74.0  34.0
學生48  94   72   92   63   86  407  81.4  10.0
學生49  98   51   67   87   54  357  71.4  44.0
學生50  84  100   90  100   87  461  92.2   1.0

In [2]:
#選擇欄位
df1 = df[['國文', '英文', '數學', '自然', '社會']]
df1

科目    國文   英文   數學   自然   社會
學生
學生1   77   93   58   51   84
學生2   89   57   53   94   65
學生3   79   79   77   82   60
學生4   85   56   81   67   87
學生5   55   96   70   58   59
學生6   98   55   97   61   82
學生7   68   59   85   94   61
學生8   76   78   74   99   79
學生9   86   85   90   92   69
學生10  97   53   73   79   70
學生11  77   94   77   59   54
學生12  79   64   63   52   68
學生13  58   52   85   70   94
學生14  87   79   93   64   75
學生15  95   65   60   79   97
學生16  88   52   61   80   93
學生17  66   80  100   66  100
學生18  96   82   96   73   97
學生19  97   76   80   50   79
學生20  69   79   55   65   77
學生21  79   94   67   59   90
學生22  80   87   52  100   82
學生23  61   78   99   57   68
學生24  62   76   81   93   98
學生25  79   75   54   93   81
學生26  54   84   52   89   79
學生27  86   70   65   80   63
學生28  89   98   90   57   51
學生29  85   91   82   74   75
學生30  96   92   82   61   70
學生31  89   73   75   84   77
學生32  85   66   80   60   93
學生33  61   87   96   90   74
學生34  98   81   64   86   70
學生35  79  100   52   82   90
學生36  90   90   79   76   87
學生37  85   85   91   81  100
學生38  77   65   52   92   77
學生39  85   87   89   63   82
學生40  69   95   85   50   95
學生41  62   65   56   86   74
學生42  54   73   56   53   66
學生43  78   63   52   94   94
學生44  58   61   60   68   79
學生45  83   54   80   81   79
學生46  90   79   94   63   91
學生47  77   58   90   90   55
學生48  94   72   92   63   86
學生49  98   51   67   87   54
學生50  84  100   90  100   87

In [16]:
s=df1.loc['學生1']
less_than_60_series=s[s<60]
#取出不及格科目
failing_subjects=less_than_60_series.index.tolist()
failing_subjects
#取出不及格科目的分數
failing_scores=less_than_60_series.tolist()
failing_scores
#建立一個Series,值要轉換為字串，如果有多個值則用逗號分隔
failing_scores_str=', '.join(map(str, failing_scores))
failing_subjects_str=', '.join(failing_subjects)
pd.Series([failing_scores_str,failing_subjects_str], index=['分數','不及格科目'])

分數       58, 51
不及格科目    數學, 自然
dtype: object

In [17]:
def apply_statistic(s):
    less_than_60_series = s[s < 60]
    # 不及格科目數量
    failing_subjects_count = less_than_60_series.count()
    # 取出不及格科目的科目
    failing_subjects = less_than_60_series.index.tolist()

    # 取出不及格科目的分數
    failing_scores = less_than_60_series.tolist()

    # 建立一個Series,值要轉換為字串，如果有多個值則用逗號分隔
    failing_scores_str = ', '.join(map(str, failing_scores))
    failing_subjects_str = ', '.join(failing_subjects)
    return pd.Series([failing_subjects_count,failing_subjects_str,failing_scores_str, ], index=['不及格科目數量','不及格科目','分數', ])
df2=df1.apply(apply_statistic, axis=1)
df2

      不及格科目數量       不及格科目          分數
學生
學生1         2      數學, 自然      58, 51
學生2         2      英文, 數學      57, 53
學生3         0
學生4         1          英文          56
學生5         3  國文, 自然, 社會  55, 58, 59
學生6         1          英文          55
學生7         1          英文          59
學生8         0
學生9         0
學生10        1          英文          53
學生11        2      自然, 社會      59, 54
學生12        1          自然          52
學生13        2      國文, 英文      58, 52
學生14        0
學生15        0
學生16        1          英文          52
學生17        0
學生18        0
學生19        1          自然          50
學生20        1          數學          55
學生21        1          自然          59
學生22        1          數學          52
學生23        1          自然          57
學生24        0
學生25        1          數學          54
學生26        2      國文, 數學      54, 52
學生27        0
學生28        2      自然, 社會      57, 51
學生29        0
學生30        0
學生31        0
學生32        0
學生33        0
學生34        0
學生35        1          數學          52
學生36        0
學生37        0
學生38        1          數學          52
學生39        0
學生40        1          自然          50
學生41        1          數學          56
學生42        3  國文, 數學, 自然  54, 56, 53
學生43        1          數學          52
學生44        1          國文          58
學生45        1          英文          54
學生46        0
學生47        2      英文, 社會      58, 55
學生48        0
學生49        2      英文, 社會      51, 54
學生50        0

In [18]:
#df要和df2合併
df_merged=pd.concat([df1, df2], axis=1)
df_merged

      國文   英文   數學   自然   社會  不及格科目數量       不及格科目          分數
學生
學生1   77   93   58   51   84        2      數學, 自然      58, 51
學生2   89   57   53   94   65        2      英文, 數學      57, 53
學生3   79   79   77   82   60        0
學生4   85   56   81   67   87        1          英文          56
學生5   55   96   70   58   59        3  國文, 自然, 社會  55, 58, 59
學生6   98   55   97   61   82        1          英文          55
學生7   68   59   85   94   61        1          英文          59
學生8   76   78   74   99   79        0
學生9   86   85   90   92   69        0
學生10  97   53   73   79   70        1          英文          53
學生11  77   94   77   59   54        2      自然, 社會      59, 54
學生12  79   64   63   52   68        1          自然          52
學生13  58   52   85   70   94        2      國文, 英文      58, 52
學生14  87   79   93   64   75        0
學生15  95   65   60   79   97        0
學生16  88   52   61   80   93        1          英文          52
學生17  66   80  100   66  100        0
學生18  96   82   96   73   97        0
學生19  97   76   80   50   79        1          自然          50
學生20  69   79   55   65   77        1          數學          55
學生21  79   94   67   59   90        1          自然          59
學生22  80   87   52  100   82        1          數學          52
學生23  61   78   99   57   68        1          自然          57
學生24  62   76   81   93   98        0
學生25  79   75   54   93   81        1          數學          54
學生26  54   84   52   89   79        2      國文, 數學      54, 52
學生27  86   70   65   80   63        0
學生28  89   98   90   57   51        2      自然, 社會      57, 51
學生29  85   91   82   74   75        0
學生30  96   92   82   61   70        0
學生31  89   73   75   84   77        0
學生32  85   66   80   60   93        0
學生33  61   87   96   90   74        0
學生34  98   81   64   86   70        0
學生35  79  100   52   82   90        1          數學          52
學生36  90   90   79   76   87        0
學生37  85   85   91   81  100        0
學生38  77   65   52   92   77        1          數學          52
學生39  85   87   89   63   82        0
學生40  69   95   85   50   95        1          自然          50
學生41  62   65   56   86   74        1          數學          56
學生42  54   73   56   53   66        3  國文, 數學, 自然  54, 56, 53
學生43  78   63   52   94   94        1          數學          52
學生44  58   61   60   68   79        1          國文          58
學生45  83   54   80   81   79        1          英文          54
學生46  90   79   94   63   91        0
學生47  77   58   90   90   55        2      英文, 社會      58, 55
學生48  94   72   92   63   86        0
學生49  98   51   67   87   54        2      英文, 社會      51, 54
學生50  84  100   90  100   87        0

In [20]:
#df_merged請儲存為excel檔
df_merged.to_excel('df_merged.xlsx')