In [2]:
import numpy as np
import pandas as pd

df=pd.DataFrame(np.arange(16).reshape(4,4),
                index=['台北','台中','台南','高雄'],
                columns=['one','two','three','four'])
df

    one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [3]:
#drop
df.drop(index=['台北','高雄'], inplace=True)
df

    one  two  three  four
台中    4    5      6     7
台南    8    9     10    11

In [4]:
#排序和排名
scores=np.random.randint(50,101,size=(50,5))
df=pd.DataFrame(scores,
                columns=['國文','英文','數學','自然','社會'],
                index=['學生'+str(i) for i in range(1,51)])
df.index.name='學生'
df.columns.name='科目'
sum_values = df.sum(axis=1)
mean_values = df.mean(axis=1)
df['總分'] = sum_values
df['平均'] = mean_values
df

科目     國文  英文   數學   自然   社會   總分    平均
學生
學生1    88  63   98   98   76  423  84.6
學生2    52  65   88   51   93  349  69.8
學生3   100  81  100   74   84  439  87.8
學生4    89  68   78   75   66  376  75.2
學生5   100  53   72   86   60  371  74.2
學生6    64  62   92   84   72  374  74.8
學生7    61  94   56   88   92  391  78.2
學生8    90  58   74   74   55  351  70.2
學生9    93  92   52   52   92  381  76.2
學生10   67  71   97   94   67  396  79.2
學生11   88  84   50   57   98  377  75.4
學生12   74  97   55   72   88  386  77.2
學生13   62  63   62   63   56  306  61.2
學生14   60  77   50   92   95  374  74.8
學生15   72  89   96   59   91  407  81.4
學生16   59  97   56   98   67  377  75.4
學生17   58  57   53   91   86  345  69.0
學生18   59  59   61   84   97  360  72.0
學生19   77  91   80   51   66  365  73.0
學生20   83  76   75   89   93  416  83.2
學生21   55  88   88   99   59  389  77.8
學生22   58  60   62   90   94  364  72.8
學生23   84  74   98   74   80  410  82.0
學生24   87  70  100   81   85  423  84.6
學生25   60  80   94   96   78  408  81.6
學生26   67  81   69   62   59  338  67.6
學生27   59  81   96   87   92  415  83.0
學生28   95  76   89   58   81  399  79.8
學生29   75  98   59   94   75  401  80.2
學生30   84  76   55   82   68  365  73.0
學生31   53  93   55   99   57  357  71.4
學生32   52  79   80  100   67  378  75.6
學生33   50  95   65   99   51  360  72.0
學生34   86  92   53   51   83  365  73.0
學生35   99  99   82   89   67  436  87.2
學生36   97  84   98   88   90  457  91.4
學生37   85  69   83   83   93  413  82.6
學生38   83  81   62   94   75  395  79.0
學生39   52  57   87   71  100  367  73.4
學生40   66  75   53   53   74  321  64.2
學生41   68  97   97   70   85  417  83.4
學生42   81  77   75   70   64  367  73.4
學生43   93  76   65   81   71  386  77.2
學生44   95  60   68   81   78  382  76.4
學生45   91  61   54   64   90  360  72.0
學生46   96  76   54   74   86  386  77.2
學生47   91  72   90   75   67  395  79.0
學生48   62  62   75   99   60  358  71.6
學生49   72  72   71   51   85  351  70.2
學生50   98  75   86   78   61  398  79.6

In [ ]:
#排序和排名
#rank()
rank_values=sum_values.rank(method='min', ascending=False)
df['排名'] = rank_values
df

科目     國文  英文   數學   自然   社會   總分    平均    排名
學生
學生13   62  63   62   63   56  306  61.2   1.0
學生40   66  75   53   53   74  321  64.2   2.0
學生26   67  81   69   62   59  338  67.6   3.0
學生17   58  57   53   91   86  345  69.0   4.0
學生2    52  65   88   51   93  349  69.8   5.0
學生49   72  72   71   51   85  351  70.2   6.0
學生8    90  58   74   74   55  351  70.2   6.0
學生31   53  93   55   99   57  357  71.4   8.0
學生48   62  62   75   99   60  358  71.6   9.0
學生18   59  59   61   84   97  360  72.0  10.0
學生33   50  95   65   99   51  360  72.0  10.0
學生45   91  61   54   64   90  360  72.0  10.0
學生22   58  60   62   90   94  364  72.8  13.0
學生34   86  92   53   51   83  365  73.0  14.0
學生30   84  76   55   82   68  365  73.0  14.0
學生19   77  91   80   51   66  365  73.0  14.0
學生39   52  57   87   71  100  367  73.4  17.0
學生42   81  77   75   70   64  367  73.4  17.0
學生5   100  53   72   86   60  371  74.2  19.0
學生6    64  62   92   84   72  374  74.8  20.0
學生14   60  77   50   92   95  374  74.8  20.0
學生4    89  68   78   75   66  376  75.2  22.0
學生11   88  84   50   57   98  377  75.4  23.0
學生16   59  97   56   98   67  377  75.4  23.0
學生32   52  79   80  100   67  378  75.6  25.0
學生9    93  92   52   52   92  381  76.2  26.0
學生44   95  60   68   81   78  382  76.4  27.0
學生46   96  76   54   74   86  386  77.2  28.0
學生43   93  76   65   81   71  386  77.2  28.0
學生12   74  97   55   72   88  386  77.2  28.0
學生21   55  88   88   99   59  389  77.8  31.0
學生7    61  94   56   88   92  391  78.2  32.0
學生38   83  81   62   94   75  395  79.0  33.0
學生47   91  72   90   75   67  395  79.0  33.0
學生10   67  71   97   94   67  396  79.2  35.0
學生50   98  75   86   78   61  398  79.6  36.0
學生28   95  76   89   58   81  399  79.8  37.0
學生29   75  98   59   94   75  401  80.2  38.0
學生15   72  89   96   59   91  407  81.4  39.0
學生25   60  80   94   96   78  408  81.6  40.0
學生23   84  74   98   74   80  410  82.0  41.0
學生37   85  69   83   83   93  413  82.6  42.0
學生27   59  81   96   87   92  415  83.0  43.0
學生20   83  76   75   89   93  416  83.2  44.0
學生41   68  97   97   70   85  417  83.4  45.0
學生24   87  70  100   81   85  423  84.6  46.0
學生1    88  63   98   98   76  423  84.6  46.0
學生35   99  99   82   89   67  436  87.2  48.0
學生3   100  81  100   74   84  439  87.8  49.0
學生36   97  84   98   88   90  457  91.4  50.0

In [10]:
#sort_value()
#sort_index()
df1=df.sort_values(by='總分', ascending=False)
df1

科目     國文  英文   數學   自然   社會   總分    平均    排名
學生
學生36   97  84   98   88   90  457  91.4  50.0
學生3   100  81  100   74   84  439  87.8  49.0
學生35   99  99   82   89   67  436  87.2  48.0
學生24   87  70  100   81   85  423  84.6  46.0
學生1    88  63   98   98   76  423  84.6  46.0
學生41   68  97   97   70   85  417  83.4  45.0
學生20   83  76   75   89   93  416  83.2  44.0
學生27   59  81   96   87   92  415  83.0  43.0
學生37   85  69   83   83   93  413  82.6  42.0
學生23   84  74   98   74   80  410  82.0  41.0
學生25   60  80   94   96   78  408  81.6  40.0
學生15   72  89   96   59   91  407  81.4  39.0
學生29   75  98   59   94   75  401  80.2  38.0
學生28   95  76   89   58   81  399  79.8  37.0
學生50   98  75   86   78   61  398  79.6  36.0
學生10   67  71   97   94   67  396  79.2  35.0
學生47   91  72   90   75   67  395  79.0  33.0
學生38   83  81   62   94   75  395  79.0  33.0
學生7    61  94   56   88   92  391  78.2  32.0
學生21   55  88   88   99   59  389  77.8  31.0
學生46   96  76   54   74   86  386  77.2  28.0
學生43   93  76   65   81   71  386  77.2  28.0
學生12   74  97   55   72   88  386  77.2  28.0
學生44   95  60   68   81   78  382  76.4  27.0
學生9    93  92   52   52   92  381  76.2  26.0
學生32   52  79   80  100   67  378  75.6  25.0
學生11   88  84   50   57   98  377  75.4  23.0
學生16   59  97   56   98   67  377  75.4  23.0
學生4    89  68   78   75   66  376  75.2  22.0
學生6    64  62   92   84   72  374  74.8  20.0
學生14   60  77   50   92   95  374  74.8  20.0
學生5   100  53   72   86   60  371  74.2  19.0
學生42   81  77   75   70   64  367  73.4  17.0
學生39   52  57   87   71  100  367  73.4  17.0
學生34   86  92   53   51   83  365  73.0  14.0
學生19   77  91   80   51   66  365  73.0  14.0
學生30   84  76   55   82   68  365  73.0  14.0
學生22   58  60   62   90   94  364  72.8  13.0
學生33   50  95   65   99   51  360  72.0  10.0
學生18   59  59   61   84   97  360  72.0  10.0
學生45   91  61   54   64   90  360  72.0  10.0
學生48   62  62   75   99   60  358  71.6   9.0
學生31   53  93   55   99   57  357  71.4   8.0
學生49   72  72   71   51   85  351  70.2   6.0
學生8    90  58   74   74   55  351  70.2   6.0
學生2    52  65   88   51   93  349  69.8   5.0
學生17   58  57   53   91   86  345  69.0   4.0
學生26   67  81   69   62   59  338  67.6   3.0
學生40   66  75   53   53   74  321  64.2   2.0
學生13   62  63   62   63   56  306  61.2   1.0